### ISSUE TITLE
Nil pointer dereferece on darwin/amd64

### ISSUE THREAD

**Issue by dorneanu** [ryo-ma/lazyhub#1]
Hi, 

first of all, thanks for this awesome tool. I really like how you decoupled all the UI relevant stuff so it can be used somewhere else. I actually used some of the components under`ui/*.go` to implement my own application. I really liked your "clean code" approach. And BTW: Why `gocui` and not `tcell` for example? `gocui` seems to have less "features". 

I wanted to actually run your tool on my Mac OS and after running it I immediately got:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x133bb7a]

goroutine 1 [running]:
github.com/ryo-ma/lazyhub/lib.(*Result).Draw(0x0, 0x1486ac0, 0xc00019e200, 0x0, 0x0)
        /Users/vdorneanu/go/src/github.com/ryo-ma/lazyhub/lib/githubclient.go:125 +0x3a
github.com/ryo-ma/lazyhub/ui.(*RepositoryPanel).DrawView(0xc00018e0c0, 0xc00018c000, 0x0, 0x0)
        /Users/vdorneanu/go/src/github.com/ryo-ma/lazyhub/ui/repository.go:34 +0x178
main.main()
        /Users/vdorneanu/go/src/github.com/ryo-ma/lazyhub/main.go:42 +0x34a
```

I didn't have the time to do some debugging. But I guess this might as well be interesting for you.

**Comment by ryo-ma** [comment]
Thank you for your issue and compliment.
I actually didn't know the `tcell` when I was developing this lazyhub.

The issue is that GitHub Trending API is not working. 
https://github.com/huchenme/github-trending-api
https://github.com/huchenme/github-trending-api/issues/130


I will be looking for other API.

**Comment by ryo-ma** [comment]
I have fixed it.
Please make sure.
https://github.com/ryo-ma/lazyhub/releases

**Comment by jonnieey** [comment]
Still getting the error.  Using arch linux, compled from source and also release binary.

**Comment by ryo-ma** [comment]
@jonnieey  API was fixed.

**Comment by jonnieey** [comment]
Yeah, it works now, thanks.
